config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'schedules/index'
  root to: "schedules#index"
  resources :users, only: [:edit, :update]
  resources :rooms do
    resources :schedules, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :candidates, only: [:index, :new, :create, :edit, :update, :destroy] do
      member do
        post :confirm
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  belongs_to :room
  belongs_to :user
  # has_many :candidate_schedules, dependent: :destroy
  # accepts_nested_attributes_for :candidate_schedules, reject_if: :all_blank, allow_destroy: true

  validates :title, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
end

app/models/candidate_schedule.rb
class CandidateSchedule < ApplicationRecord
  belongs_to :candidate
  validates :start_time, presence: true
  validates :end_time, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_users, dependent: :destroy
  has_many :users, through: :room_users
  has_many :schedules, dependent: :destroy
  has_many :candidates, dependent: :destroy

  validates :room_name, presence: true
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :room
  belongs_to :user

  validates :title, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :room_users
  has_many :rooms, through: :room_users
  has_many :schedules
  has_many :candidates

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_room, only: [:new, :create, :edit, :update]
  before_action :set_candidate, only: [:edit, :update, :destroy, :confirm]

  def index
    @rooms = current_user.rooms.includes(:user)
    @candidate = Candidate.new
    @candidates = current_user.candidates.includes(:user, :room)
  end

  def new
    @candidate = Candidate.new
    @candidates = Candidate.all
  end

  def create
    @candidate = @room.candidates.new(candidate_params)
    if @candidate.save
      redirect_to root_path(@room)
    else
      @candidates = @room.candidates.includes(:user)
      render :new
    end
  end

  def edit
  end

  def update
    @candidate.update(candidate_params)
    if @candidate.save
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @candidate.destroy
    redirect_to root_path
  end

  def confirm
    @schedule = Schedule.new(
      title: @candidate.title,
      body: @candidate.body,
      start_time: @candidate.start_time,
      end_time: @candidate.end_time,
      room_id: @candidate.room_id,
      user_id: @candidate.user_id
    )
    if @schedule.save
      @candidate.destroy
      redirect_to root_path, notice: '予定が確定されました。'
    end
  end

  private

  def candidate_params
    params.require(:candidate).permit(:title, :body, :start_time, :end_time).merge(user_id: current_user.id)
  end

  def find_room
    @room = Room.find(params[:room_id])
  end

  def set_candidate
    @candidate = Candidate.find(params[:id])
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  def index
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to room_path(@room)
    else
      render :new
    end
  end

  def show
    @schedules = @room.schedules
    @candidates = @room.candidates
  end

  def edit
  end

  def update
    if @room.update(room_params)
      redirect_to @room
    else
      render :edit
    end
  end

  def destroy
    @room.destroy
    redirect_to root_path
  end

  private

  def room_params
    params.require(:room).permit(:room_name, :description, user_ids: [])
  end

  def set_room
    @room = Room.find(params[:id])
  end

end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_room, only: [:new, :create, :edit, :update]
  before_action :set_schedule, only: [:edit, :update, :destroy]

  def index
    @rooms = current_user.rooms.includes(:user)
    @schedule = Schedule.new
    @schedules = current_user.schedules.includes(:user, :room)
    @candidates = current_user.candidates.includes(:user, :room)
  end

  def new
    @schedule = Schedule.new
    @schedules = Schedule.all
  end

  def create
    @schedule = @room.schedules.new(schedule_params)
    if @schedule.save
      redirect_to room_schedules_path(@room)
    else
      @schedules = @room.schedules.includes(:user)
      render :new
    end
  end

  def edit
  end

  def update
    @schedule.update(schedule_params)
    if @schedule.save
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @schedule.destroy
    redirect_to root_path
  end

  private

  def schedule_params
    params.require(:schedule).permit(:title, :body, :start_time, :end_time).merge(user_id: current_user.id)
  end

  def find_room
    @room = Room.find(params[:room_id])
  end

  def set_schedule
    @schedule = Schedule.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def update
    current_user.update(user_params)
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/candidates/_form.html.erb
<div class='chat-room-form__field'>
  <div class='chat-room-form__field--left'>
    <label class='chat-room-form__label'>グループメンバー</label>
  </div>
  <div class='chat-room-form__field--right'>
    <% @room.users.each do |user| %>
      <div><%= user.name %></div>
    <% end %>
  </div>
</div>
<%=form_with model: [@room, @candidate], local: true do |f|%>
  <div class='chat-room-form__field'>
    <div class='chat-room-form__field--left'>
      <%= f.label :title, :タイトル, class: 'chat-room-form__label'%>
    </div>
    <div class='chat-room-form__field--right'>
      <%= f.text_field :title, class: 'chat__room_name chat-room-form__input', placeholder: 'スケジュール内容を入力してください'%>
    </div>
  </div>
  <div class='chat-room-form__field'>
    <div class='chat-room-form__field--left'>
      <%= f.label :body, :スケジュールの詳細, class: 'chat-room-form__label'%>
    </div>
    <div class='chat-room-form__field--right'>
      <%= f.text_field :body, class: 'chat__room_name chat-room-form__input', placeholder: 'スケジュールの詳細を入力してください'%>
    </div>
  </div>
  <div class='chat-room-form__field'>
    <div class='chat-room-form__field--left'>
      <%= f.label :start_time, :開始, class: 'chat-room-form__label'%>
    </div>
    <div class='chat-room-form__field--right'>
      <%= f.datetime_field :start_time, class: 'chat__room_name chat-room-form__input', placeholder: '開始時刻を選択してください'%>
    </div>
  </div>
  <div class='chat-room-form__field'>
    <div class='chat-room-form__field--left'>
      <%= f.label :end_time, :終了, class: 'chat-room-form__label'%>
    </div>
    <div class='chat-room-form__field--right'>
      <%= f.datetime_field :end_time, class: 'chat__room_name chat-room-form__input', placeholder: '終了時刻を選択してください'%>
    </div>
  </div>
  <div class='chat-room-form__field'>
    <div class='chat-room-form__field--left'></div>
    <div class='chat-room-form__field--right'>
      <%= f.submit "候補を登録", class: 'chat-room-form__action-btn'%>
    </div>
  </div>
<% end %>

app/views/candidates/edit.html.erb
<div class="wrapper">
  <%= render "schedules/header" %>

  <div class="side_bar">
      <%= render "schedules/side_bar" %>
  </div>

  <div class='chat-room-form'>
    <h1>スケジュール編集</h1>
      <%= render partial: "form", locals: { candidate: @candidate } %>
  </div>
</div>

app/views/candidates/new.html.erb
<div class="wrapper">
  <%= render "schedules/header" %>

  <div class="side_bar">
      <%= render "schedules/side_bar" %>
  </div>

  <div class='chat-room-form'>
    <h1>スケジュール候補</h1>
      <%= render partial: "form", locals: { candidate: @candidate } %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Scheduleapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/dashboard/">

    <!-- Bootstrap CSS -->
    <link href="../bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <link href="dashboard.css" rel="stylesheet">

  </head>

  <body>
    <%= yield %>

    <script src="../bootstrap/js/jquery-3.7.0.min.js"></script>
    <script src="../bootstrap/js/bootstrap.bundle.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script><script src="dashboard.js"></script>
  </body>
</html>

app/views/rooms/_form.html.erb
<%=form_with model: @room, local: true do |f|%>
  <div class='chat-room-form__field'>
    <div class='chat-room-form__field--left'>
      <%= f.label :room_name, :グループ名, class: 'chat-room-form__label'%>
    </div>
    <div class='chat-room-form__field--right'>
      <%= f.text_field :room_name, class: 'chat__room_name chat-room-form__input', placeholder: 'グループ名を入力してください'%>
    </div>
  </div>
  <div class='chat-room-form__field'>
    <div class='chat-room-form__field--left'>
      <%= f.label :description, :グループの詳細, class: 'chat-room-form__label'%>
    </div>
    <div class='chat-room-form__field--right'>
      <%= f.text_field :description, class: 'chat__room_name chat-room-form__input', placeholder: 'グループの詳細を入力してください'%>
    </div>
  </div>
  <div class='chat-room-form__field'>
  </div>
  <div class='chat-room-form__field'>
    <div class='chat-room-form__field--left'>
      <label class='chat-room-form__label' for='chat_room_チャットメンバー'>グループメンバー</label>
    </div>
    <div class='chat-room-form__field--right'>
        <input type="checkbox" name="room[user_ids][]" value="<%= current_user.id %>" checked>
        <%= current_user.name %><br>
        <% User.where.not(id: current_user.id).each do |user| %>
          <input type="checkbox" name="room[user_ids][]" value="<%= user.id %>">
          <%= user.name %><br>
        <% end %>
      <%# <input name="room[user_ids][]" type="hidden" value=<%= current_user.id %>
    </div>
  </div>
  <div class='chat-room-form__field'>
    <div class='chat-room-form__field--left'></div>
    <div class='chat-room-form__field--right'>
      <%= f.submit "グループを登録", class: 'chat-room-form__action-btn'%>
    </div>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<div class="wrapper">
  <%= render "schedules/header" %>

  <div class="side_bar">
      <%= render "schedules/side_bar" %>
  </div>

  <div class='chat-room-form'>
    <h1>グループ編集</h1>
    <%= render partial: "form", locals: { room: @room } %>
  </div>
</div>

app/views/rooms/index.html.erb
<div class="wrapper">
  <%= render "schedules/header" %>
  
  <div class="side_bar">
      <%= render "schedules/side_bar" %>
  </div>

  <%= month_calendar schedules: @schedules do |date, schedules| %>
    <%= date.day %>
      <% @schedules.each do |schedule| %>
        <% if schedule.start_time.to_date == date %>
          <%= schedule.title %>
        <% end %>
      <% end %>
  <% end %>
  <%# <%= link_to "スケジュール作成", new_room_schedule_path(@room), class: "nav-link" %> %>
</div>

app/views/rooms/new.html.erb
<div class="wrapper">
  <%= render "schedules/header" %>

  <div class="side_bar">
      <%= render "schedules/side_bar" %>
  </div>

  <div class='chat-room-form'>
    <h1>新規グループ</h1>
    <%=form_with model: @room, local: true do |f|%>
      <div class='chat-room-form__field'>
        <div class='chat-room-form__field--left'>
          <%= f.label :room_name, :グループ名, class: 'chat-room-form__label'%>
        </div>
        <div class='chat-room-form__field--right'>
          <%= f.text_field :room_name, class: 'chat__room_name chat-room-form__input', placeholder: 'グループ名を入力してください'%>
        </div>
      </div>
      <div class='chat-room-form__field'>
        <div class='chat-room-form__field--left'>
          <%= f.label :description, :グループの詳細, class: 'chat-room-form__label'%>
        </div>
        <div class='chat-room-form__field--right'>
          <%= f.text_field :description, class: 'chat__room_name chat-room-form__input', placeholder: 'グループの詳細を入力してください'%>
        </div>
      </div>
      <div class='chat-room-form__field'>
      </div>
      <div class='chat-room-form__field'>
        <div class='chat-room-form__field--left'>
          <label class='chat-room-form__label' for='chat_room_チャットメンバー'>グループメンバー</label>
        </div>
        <div class='chat-room-form__field--right'>
            <input type="checkbox" name="room[user_ids][]" value="<%= current_user.id %>" checked>
            <%= current_user.name %><br>
            <% User.where.not(id: current_user.id).each do |user| %>
              <input type="checkbox" name="room[user_ids][]" value="<%= user.id %>">
              <%= user.name %><br>
            <% end %>
          <%# <input name="room[user_ids][]" type="hidden" value=<%= current_user.id %>
        </div>
      </div>
      <div class='chat-room-form__field'>
        <div class='chat-room-form__field--left'></div>
        <div class='chat-room-form__field--right'>
          <%= f.submit class: 'chat-room-form__action-btn'%>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="wrapper">
  <%= render "schedules/header" %>

  <div class="side_bar">
      <%= render "schedules/side_bar" %>
  </div>

  <div class="main_calender">
    <%= render "schedules/main_calender" %>
  </div>
</div>

app/views/schedules/_form.html.erb
<div class='chat-room-form__field'>
  <div class='chat-room-form__field--left'>
    <label class='chat-room-form__label'>グループメンバー</label>
  </div>
  <div class='chat-room-form__field--right'>
    <% @room.users.each do |user| %>
      <div><%= user.name %></div>
    <% end %>
  </div>
</div>
<%=form_with model: [@room, @schedule], local: true do |f|%>
  <div class='chat-room-form__field'>
    <div class='chat-room-form__field--left'>
      <%= f.label :title, :タイトル, class: 'chat-room-form__label'%>
    </div>
    <div class='chat-room-form__field--right'>
      <%= f.text_field :title, class: 'chat__room_name chat-room-form__input', placeholder: 'スケジュール内容を入力してください'%>
    </div>
  </div>
  <div class='chat-room-form__field'>
    <div class='chat-room-form__field--left'>
      <%= f.label :body, :スケジュールの詳細, class: 'chat-room-form__label'%>
    </div>
    <div class='chat-room-form__field--right'>
      <%= f.text_field :body, class: 'chat__room_name chat-room-form__input', placeholder: 'スケジュールの詳細を入力してください'%>
    </div>
  </div>
  <div class='chat-room-form__field'>
    <div class='chat-room-form__field--left'>
      <%= f.label :start_time, :開始, class: 'chat-room-form__label'%>
    </div>
    <div class='chat-room-form__field--right'>
      <%= f.datetime_field :start_time, class: 'chat__room_name chat-room-form__input', placeholder: '開始時刻を選択してください'%>
    </div>
  </div>
  <div class='chat-room-form__field'>
    <div class='chat-room-form__field--left'>
      <%= f.label :end_time, :終了, class: 'chat-room-form__label'%>
    </div>
    <div class='chat-room-form__field--right'>
      <%= f.datetime_field :end_time, class: 'chat__room_name chat-room-form__input', placeholder: '終了時刻を選択してください'%>
    </div>
  </div>
  <div class='chat-room-form__field'>
    <div class='chat-room-form__field--left'></div>
    <div class='chat-room-form__field--right'>
      <%= f.submit class: 'chat-room-form__action-btn'%>
    </div>
  </div>
<% end %>

app/views/schedules/_header.html.erb
<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <%= link_to 'scheduleapp', root_path, class: "navbar-brand col-md-3 col-lg-2 me-0 px-3" %>
  <%# <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation"> %>
    <%# <span class="navbar-toggler-icon"></span> %>
  <%# </button> %>
  <%# <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search"> %>
  <div class="navbar-nav">
    <div class="nav-item text-nowrap">
      <li><%= link_to current_user.name, edit_user_path(current_user), class: "nav-link px-3" %></li>
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "nav-link px-3" %></li>
    </div>
  </div>
</header>

app/views/schedules/_main_calender.html.erb
<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <% if @room %>
      <h1 class="h2"><%= @room.room_name %></h1>
      <div class='chat-room-form__field'>
        <div class='chat-room-form__field--left'>
          <label class='chat-room-form__label'></label>
        </div>
        
      </div>
    <% else %>
      <h1 class="h2">スケジュール一覧</h1>
    <% end %>

    <div class="btn-toolbar mb-2 mb-md-0">
      <% if @room %>
        <div class="btn-group me-2">
          <button type="button" class="btn btn-sm btn-outline-secondary">
            <%= link_to "スケジュール作成", new_room_schedule_path(@room), class: "nav-link" %>
          </button>
          <button type="button" class="btn btn-sm btn-outline-secondary">
            <%= link_to "候補作成", new_room_candidate_path(@room), class: "nav-link" %>
          </button>
        </div>
        <div class="btn-group me-2">
          <button type="button" class="btn btn-sm btn-outline-secondary">
            <%= link_to "グループ編集", edit_room_path(@room), class: "nav-link" %>
          </button>
          <button type="button" class="btn btn-sm btn-outline-secondary">
            <%= link_to "削除", room_path(@room), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "nav-link" %>
          </button>
        </div>
      <% end %>
    </div>
  </div>

    <%= month_calendar schedules: @schedules do |date, schedules| %>
      <%= date.in_time_zone("Asia/Tokyo").day %>
        <% @schedules.each do |schedule| %>
          <% start_date = schedule.start_time.to_date %>
          <% end_date = schedule.end_time.to_date %>
          <% if start_date <= date && date <= end_date %>
            <span class="schedule-list"><br>・<%= schedule.title %></span>
          <% end %>
        <% end %>
        <% @candidates.each do |candidate| %>
          <% start_date = candidate.start_time.to_date %>
          <% end_date = candidate.end_time.to_date %>
          <% if start_date <= date && date <= end_date %>
            <span class="candidate-list"><br>・（仮）<%= candidate.title %></span>
          <% end %>
        <% end %>
    <% end %>

  <% if @room %>
    <h4>グループ詳細</h4>
    <div class="table-responsive">
      <%= @room.description %>
    </div>
  <% end %>
  <h4>予定一覧</h4>
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th scope="col">タイトル</th>
          <th scope="col">グループ</th>
          <th scope="col">開始</th>
          <th scope="col">終了</th>
          <th scope="col">スケジュールの詳細</th>
          <% if @room %>
            <th scope="col">操作</th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @schedules.where("start_time >= ?", Date.today).order(start_time: :asc).each do |schedule| %>
          <tr>
            <td><%= schedule.title %></td>
            <td><%= link_to schedule.room.room_name, room_path(schedule.room) %></td>
            <td><%= schedule.start_time.in_time_zone("Asia/Tokyo").strftime("%Y-%m-%d %H:%M") %></td>
            <td><%= schedule.end_time.in_time_zone("Asia/Tokyo").strftime("%Y-%m-%d %H:%M") %></td>
            <td><%= schedule.body %></td>
            <% if @room %>
              <td>
                <%= link_to "編集", edit_room_schedule_path(@room, schedule), class: "btn btn-sm btn-outline-secondary" %>
                <%= link_to "削除", room_schedule_path(@room, schedule), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-sm btn-outline-secondary" %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  <h4>調整中の予定</h4>
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th scope="col">タイトル</th>
          <th scope="col">グループ</th>
          <th scope="col">開始</th>
          <th scope="col">終了</th>
          <th scope="col">スケジュールの詳細</th>
          <% if @room %>
            <th scope="col">参加可能</th>
            <th scope="col">操作</th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @candidates.where("start_time >= ?", Date.today).order(start_time: :asc).each do |candidate| %>
          <tr>
            <td><%= candidate.title %></td>
            <td><%= link_to candidate.room.room_name, room_path(candidate.room) %></td>
            <td><%= candidate.start_time.in_time_zone("Asia/Tokyo").strftime("%Y-%m-%d %H:%M") %></td>
            <td><%= candidate.end_time.in_time_zone("Asia/Tokyo").strftime("%Y-%m-%d %H:%M") %></td>
            <td><%= candidate.body %></td>
            <% if @room %>
              <td>
                <ul class="nav flex-column">
                  <% @room.users.each do |user| %>
                    <li><div class="nav-link"><%= user.name %></div></li>
                  <% end %>
                </ul>
              </td>
              <td>
                <%= link_to "確定", confirm_room_candidate_path(@room, candidate), method: :post, data: { confirm: "候補を確定しますか？" }, class: "btn btn-sm btn-outline-secondary" %>
                <%= link_to "編集", edit_room_candidate_path(@room, candidate), class: "btn btn-sm btn-outline-secondary" %>
                <%= link_to "削除", room_candidate_path(@room, candidate), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-sm btn-outline-secondary" %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
</main>

app/views/schedules/_side_bar.html.erb
<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
  <div class="position-sticky pt-3">
    <ul class="nav flex-column">
      <div class="nav-item">
        <li><%= link_to "新規グループ作成", new_room_path, class: "nav-link" %></li>
      </div>
      <% current_user.rooms.each do |room| %>
        <div class="nav-item">
          <li><%= link_to room.room_name, room_path(room), class: "nav-link" %></li>
        </div>
      <% end %>
    </ul>

    <% if @room %>
      <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
        <span>グループメンバー</span>
        <a class="link-secondary" href="#" aria-label="Add a new report">
          <span data-feather="plus-circle"></span>
        </a>
      </h6>
      <ul class="nav flex-column">
        <% @room.users.each do |user| %>
          <li><div class="nav-link"><%= user.name %></div></li>
        <% end %>
      </ul>
    <% end %>
  </div>
</nav>

app/views/schedules/edit.html.erb
<div class="wrapper">
  <%= render "schedules/header" %>

  <div class="side_bar">
      <%= render "schedules/side_bar" %>
  </div>

  <div class='chat-room-form'>
    <h1>スケジュール編集</h1>
      <%= render partial: "form", locals: { schedule: @schedule } %>
  </div>
</div>

app/views/schedules/index.html.erb
<div class="wrapper">

  <%= render "header" %>

    <div class="side_bar">
      <%= render "side_bar" %>
    </div>

    <div class="main_calender">
      <%= render "main_calender" %>
    </div>

  

</div>

app/views/schedules/new.html.erb
<div class="wrapper">
  <%= render "schedules/header" %>

  <div class="side_bar">
      <%= render "schedules/side_bar" %>
  </div>

  <div class='chat-room-form'>
    <h1>新規スケジュール</h1>
      <%= render partial: "form", locals: { schedule: @schedule } %>
  </div>
</div>

app/views/schedules/show.html.erb
<div class="wrapper">
  <%= render "header" %>

  <div class="side_bar">
      <%= render "side_bar" %>
  </div>

  <div class="main_calender">
    <%= render "main_calender" %>
  </div>
</div>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'%>
      <%= link_to "トップページに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>